# Generated by Django 5.0.9 on 2024-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_argument', models.CharField(max_length=150, unique=True, verbose_name='Название аргумента')),
                ('description_argument', models.TextField(verbose_name='Описание аргумента')),
            ],
            options={
                'verbose_name': 'Аргумент',
                'verbose_name_plural': 'Аргументы',
            },
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='name_tag',
        ),
        migrations.AddField(
            model_name='question',
            name='arguments',
            field=models.ManyToManyField(related_name='arguments_method', to='bot.argument', verbose_name='Аргументы методов'),
        ),
    ]
