# Generated by Django 5.0.9 on 2024-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_argument_rename_name_tag_name_tag_question_arguments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='arguments',
        ),
        migrations.AddField(
            model_name='question',
            name='syntax',
            field=models.TextField(blank=True, null=True, verbose_name='Синтаксис'),
        ),
        migrations.DeleteModel(
            name='Argument',
        ),
    ]
