# Generated by Django 5.0.9 on 2024-11-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_question_arguments_question_syntax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name_tag',
            new_name='name',
        ),
    ]
