# Generated by Django 5.0.9 on 2025-01-29 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_name_tag_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True, verbose_name='Уровень сложности')),
                ('notification', models.BooleanField(default=False, verbose_name='Состояние уведомлений')),
                ('notification_time', models.TimeField(blank=True, null=True, verbose_name='Время уведомлений')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.UniqueConstraint(fields=('user', 'tag'), name='unique_user_tag'),
        ),
    ]
