# Generated by Django 5.0.9 on 2025-01-29 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_usersettings_usersettings_unique_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notification_time',
            field=models.TimeField(blank=True, default=datetime.time(7, 0), verbose_name='Время уведомлений'),
        ),
    ]
