# Generated by Django 5.0.9 on 2025-02-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_usersettings_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=20, null=True, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='tag',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.tag', verbose_name='Тема'),
        ),
    ]
