# Generated by Django 5.0.9 on 2025-02-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_usersettings_difficulty_alter_usersettings_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='difficulty',
            field=models.CharField(blank=True, default='easy', max_length=20, null=True, verbose_name='Уровень сложности'),
        ),
    ]
