repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      # Запуск линтера Ruff
      - id: ruff
        args: [--fix, --config=ruff_config/prod/pyproject.toml]
      # Запуск форматтера Ruff
      - id: ruff-format
        args: [--config=ruff_config/prod/pyproject.toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key
