STICKERS = {
    'perfect': [
        'CAACAgIAAxkBAAENs5NnoHwN_fQK5MT_vCSrnaHZVyXqhQACRQwAAnqdmEo2Geh166RTLDYE',
        'CAACAgIAAxkBAAENs5VnoHxNTjh4pLTeFkDsiOqXBaxxKgACFQADwDZPE81WpjthnmTnNgQ',
        'CAACAgIAAxkBAAENs5dnoHyEBDMrTUi6pa7AOMADKC21rQACRgADUomRI_j-5eQK1QodNgQ',
        'CAACAgIAAxkBAAENs5lnoHy5bbz_dbtPr_FNM_MfOr_qfgACAQEAAiI3jgRNjXmEnb5XnzYE',
        'CAACAgIAAxkBAAENs5tnoHzW8YqI8JgeuAn_EilgMJiLeQACFAMAAm2wQgN6toSoUcXpNjYE'
    ],
    'great': [
        'CAACAgIAAxkBAAENs6hnoH7vGfPUDQvXMHF0wdkD9fv9aAACaQ0AAu7v-EvzltTRAAHwpUw2BA',
        'CAACAgIAAxkBAAENs69noH8MCkxIWPM51P2LivhF3NYNDAAC6gcAAkb7rASUHp5Nfp3HaDYE',
        'CAACAgIAAxkBAAENs7FnoH8-x4Pzh8RfwIGFbzdjiuSK6gACawADlp-MDjLiqoj24Z4lNgQ',
        'CAACAgIAAxkBAAENs7NnoH9tQxjO4E_PR7Zgs1QwPNLI_wACLgkAAhhC7ghmx6Iwr7yx9DYE',
        'CAACAgEAAxkBAAENs7lnoH_0vcsm9CFEKS43itzQnpgdpgACLgEAAmlAwUU75COP0TwvfDYE'
    ],
    'good': [
        'CAACAgIAAxkBAAENs8BnoICOGw9UvyJCDc3wHTs6nwe3wQACDwwAAuKOOUotFzfMTUK3UDYE',
        'CAACAgIAAxkBAAENs8JnoICwoeiuCdBlf4x4tqCfOKnYygACfQAD9wLIDy7JuwrdyyJJNgQ',
        'CAACAgIAAxkBAAENs8RnoIDYUixZqheGf6MevdQpM2gDHgACTgEAAjDUnRFSzKY2j-x6BTYE',
        'CAACAgIAAxkBAAENs8ZnoIEeZzLb3KhIAgcNS_JCVu5JUQACdwAD5KDOByXioFEygRyrNgQ',
        'CAACAgIAAxkBAAENs8hnoIGEMoTuzYvgterSUW_DMjbgxgACDQADr8ZRGj7pvDy3DEgWNgQ'
    ]
}
